### PR TITLE
Feature/completion

### PR DESCRIPTION
**Pull request by guillaumesoldera**
Add completion support for Golo 2.0.0.
Following elements can be proposed : 
- keywords
- parameters and local variable in golo functions
- named augmentations
- module elements (functions...)
- imported module elements
- static elements for imported Java class
- available module in import scope

### CODE REVIEW

**Comment by jponge** [comment]
@guillaumesoldera You're the expert and you should have commit rights now :+1:

**Comment by jponge** [comment]
Feel free to merge these PRs

**Comment by jponge** [comment]
@guillaumesoldera Is there a place where we can download a pre-built plugin?

**Comment by guillaumesoldera** [comment]
feature/completion branch merged.
A pre-built plugin with two branches merged is not yet available. I'll give you place where download it as soon as possible.

**Comment by jponge** [comment]
Cool!

**Comment by k33g** [comment]
:+1:  I can't wait :smile:

**Comment by guillaumesoldera** [comment]
plugin is available at https://s3-eu-west-1.amazonaws.com/serli/org-gololang-netbeans.nbm !

**Comment by jponge** [comment]
:+1:

**Pull request merged**
